# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16UgYKNo_c_4EPEeRVfusDd8m3ThJlhXb
"""

# Quiz App

questions = [
    {
        "question": "Question 01: Who invented the abacus?",
        "options": [
            "1) Charles Babbage",
            "2) John Cena",
            "3) The Undertaker"
        ],
        "correct_answer": "1"
    },
    {
        "question": "Question 02: What is the capital of France?",
        "options": [
            "1) Paris",
            "2) London",
            "3) Rome"
        ],
        "correct_answer": "1"
    },
    {
        "question": "Question 03: What is the largest planet in our solar system?",
        "options": [
            "1) Earth",
            "2) Jupiter",
            "3) Saturn"
        ],
        "correct_answer": "2"
    },
    {
        "question": "Question 04: Who wrote 'To Kill a Mockingbird'?",
        "options": [
            "1) Harper Lee",
            "2) Mark Twain",
            "3) J.K. Rowling"
        ],
        "correct_answer": "1"
    },
    {
        "question": "Question 05: What is the chemical symbol for gold?",
        "options": [
            "1) Au",
            "2) Ag",
            "3) Pb"
        ],
        "correct_answer": "1"
    },
    {
        "question": "Question 06: Who painted the Mona Lisa?",
        "options": [
            "1) Leonardo da Vinci",
            "2) Vincent van Gogh",
            "3) Pablo Picasso"
        ],
        "correct_answer": "1"
    },
    {
        "question": "Question 07: What is the hardest natural substance on Earth?",
        "options": [
            "1) Diamond",
            "2) Gold",
            "3) Iron"
        ],
        "correct_answer": "1"
    },
    {
        "question": "Question 08: What is the largest ocean on Earth?",
        "options": [
            "1) Atlantic Ocean",
            "2) Indian Ocean",
            "3) Pacific Ocean"
        ],
        "correct_answer": "3"
    },
    {
        "question": "Question 09: Who is known as the 'Father of Computers'?",
        "options": [
            "1) Charles Babbage",
            "2) Alan Turing",
            "3) Bill Gates"
        ],
        "correct_answer": "1"
    },
    {
        "question": "Question 10: What is the speed of light?",
        "options": [
            "1) 299,792 km/s",
            "2) 150,000 km/s",
            "3) 300,000 km/s"
        ],
        "correct_answer": "1"
    }
]
score = 0
def administerquiz(questions):
    global score
    print("Welcome to the Quiz marks = 10")
    for q in questions:
        print(q["question"])
        print()
        for option in q["options"]:
            print(option)
        print()
        answer = input("Enter your answer ").strip()
        if answer.lower() == q["correct_answer"].lower():
            print("Your answer is correct.")
            score += 1
        else:
            print("Your answer is wrong.")
        print()


administerquiz(questions)

print("Your final score is:", score, "out of", len(questions))